# Generated by Django 2.2.6 on 2020-02-25 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimerApellido', models.CharField(max_length=35)),
                ('SegundoApellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('CedulaCiudadania', models.CharField(max_length=12)),
                ('FechaNacimiento', models.DateField()),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('CorreoElectronico', models.EmailField(max_length=254)),
                ('FechaExpedicionCedula', models.DateField()),
                ('TelefonoContacto', models.CharField(help_text='Ingresa número de contacto', max_length=14)),
                ('DireccionResidencia', models.CharField(max_length=40)),
                ('Ciudad', models.CharField(max_length=60)),
                ('Departamento', models.CharField(max_length=30)),
                ('Pais', models.CharField(max_length=50)),
                ('ReferenciaPersonal', models.CharField(max_length=50)),
                ('TelefonoReferencia', models.CharField(help_text='Ingresa número de contacto', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Rango', models.PositiveSmallIntegerField()),
                ('Estado', models.CharField(choices=[('A', 'Aprobado'), ('P', 'Pendiente'), ('R', 'Rechazado'), ('T', 'Trámite')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaSolicitud', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.Cliente')),
                ('TipoCredito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.TipoCredito')),
            ],
        ),
    ]
